language: generic

sudo: required

services:
  - docker

script:
  - docker build -t maxx09/docker-backend ./backend
  - docker build -t maxx09/docker-nginx ./nginx

after_success:
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push maxx09/docker-backend
  - docker push maxx09/docker-nginx